### ISSUE TITLE
readm not oppening documentation

### ISSUE THREAD

**Issue by IOR88** [TECHS-Technological-Solutions/ocpi#16]
Hi @HAkhavan71 the link to documentation 

Documents

[`Documentation <https://techs-technological-solutions.github.io/ocpi/`_](https://github.com/TECHS-Technological-Solutions/ocpi#id1)

is not redirecting anywhere ?

**Comment by IOR88** [comment]
I mean in the READM.md main page

**Comment by HAkhavan71** [comment]
fixed, there was a syntax error in readme
