### ISSUE TITLE
Adapter documentation and eMSP

### ISSUE THREAD

**Issue by evcharger** [TECHS-Technological-Solutions/ocpi#21]
Hello,
I managed to get this up and running and I was wondering if you have a more detailed documentation of the adapters and the data format for them? As far as I see, the adapter receives data input in a simple format and outputs as per OCPI schemas?
Also do you plan on updating with the eMSP role?
Keep up the good work!

**Comment by HamedAkhavan** [comment]
Hi @evcharger, yes the adapter will adapt data to OCPI compatible schemas.
we'll improve the library and the documentation soon.
Thank you for your kind support
