### ISSUE TITLE
sample suggestions for setting up the infrastructure(database) layer ?

### ISSUE THREAD

**Issue by statiqantriksh** [TECHS-Technological-Solutions/ocpi#33]
Best practice to setup an infrastructure layer in this project to be compatible with a relational database

**Comment by HamedAkhavan** [comment]
Hi @statiqantriksh,
let's assume that we want to use SQLAlchemy for database connection. and we have an ORM model called **Location** for the location records stored in our database. the following will be a sample for _get()_ method in CRUD class using a database connection for retrieving a location.

```python
from sqlalchemy import create_engine, select
from sqlalchemy.orm import Session

# an Engine, which the Session will use for connection resources
engine = create_engine("postgresql+psycopg2://scott:tiger@localhost/")


class Crud:
    @classmethod
    async def get(cls, module: enums.ModuleID, role: enums.RoleEnum, id, *args, **kwargs):
        # create session and get object
        with Session(engine) as session:
            return session.get(Location, id)
```

**Comment by statiqantriksh** [comment]
@HamedAkhavan 
Thank you for the reply, 
The above sample aligns with what I'm trying to achieve here.
