### ISSUE TITLE
module initialization as done in examples > v_2_2_1.py

### ISSUE THREAD

**Issue by statiqantriksh** [TECHS-Technological-Solutions/ocpi#34]
- Do we need to create a separate file with separate Crud and Adapter class for each module like its done for locations?
      - if yes then how would one go about initialize the app = get_application() from those different files
  If the above is entirely not possible then what is the best way to initialize all modules with their crud and adapter

**Comment by HamedAkhavan** [comment]
@statiqantriksh,
we will have only one Crud and one Adapter class for the entire app. the Crud methods will receive the module ID as a parameter and return value should be decided based on method input parameters
