### ISSUE TITLE
dimensions misspelling

### ISSUE THREAD

**Issue by statiqantriksh** [TECHS-Technological-Solutions/ocpi#35]
the "dimensions" word is misspelled in the below mentioned files.

- tests\test_modules\test_cdrs
- tests\test_modules\test_sessions
- py_ocpi\modules\cdrs\v_2_2_1\schemas

**Comment by HamedAkhavan** [comment]
Hi @statiqantriksh,
thanks for addressing that, we'll fix it in the next release. and btw please feel free to create a pull request to our develop branch
