### ISSUE TITLE
Information request 

### ISSUE THREAD

**Issue by statiqantriksh** [TECHS-Technological-Solutions/ocpi#38]
@HamedAkhavan 
In cpo.py in command module can you please explain the relevance from the below mentioned code for 2, 3 and 4 points

    try:
        
     1.   if hasattr(command_data, 'location_id'):
     2.      await crud.get(ModuleID.locations, RoleEnum.cpo, command_data.location_id, auth_token=auth_token,
                            version=VersionNumber.v_2_2_1)  //THIS is never referenced 

      3.   command_response = await crud.do(ModuleID.commands, RoleEnum.cpo, Action.send_command, command_data.dict(),
                                            command=command, auth_token=auth_token, version=VersionNumber.v_2_2_1)

      4. background_tasks.add_task(send_command_result, response_url=command_data.response_url,
                                    command=command, auth_token=auth_token, crud=crud, adapter=adapter)

**Comment by HamedAkhavan** [comment]
Hi @statiqantriksh,
1,2: if the command is intended for a specific location then the location must be checked to be valid. like unlock connecteor:
![image](https://user-images.githubusercontent.com/61178707/215408970-2e28ccd5-5491-4934-8e9e-942fee2388ad.png)
3,4: when a command is requested the command response will be returned to acknowledge the request. after responding to the request the command result must be sent to the sender in a separate request. we're using fastapi background task for sending command result.
please check [commands flow](https://github.com/ocpi/ocpi/blob/2.2.1/mod_commands.asciidoc#11-flow) for further information.

**Comment by statiqantriksh** [comment]
Thank you @HamedAkhavan, this clarifies it.
