### ISSUE TITLE
Query: What is the expected response from an emsp upon PUT or PATCH of session object for charging period  

### ISSUE THREAD

**Issue by statiqantriksh** [TECHS-Technological-Solutions/ocpi#41]
@HamedAkhavan 
- Unclear from the documentation on the expected response from an emsp when 

1. PUT for the session object 
2. PATCH for the charging periods

**Comment by HamedAkhavan** [comment]
@statiqantriksh better to ask this question on [OCPI issues](https://github.com/ocpi/ocpi/issues)

**Comment by statiqantriksh** [comment]
Thank you
