### ISSUE TITLE
Datetime validation issue 

### ISSUE THREAD

**Issue by statiqantriksh** [TECHS-Technological-Solutions/ocpi#42]
@HamedAkhavan 
The Datetime type in data_types throws error for timestamp "2023-02-06T12:27:31.276Z" which is a valid time stamp type specified in the documentation 

![techs-invalid-timestamp](https://user-images.githubusercontent.com/118425314/217076280-ac5eafc2-02fe-4240-be39-5f8d714683e6.png)

**Comment by HamedAkhavan** [comment]
Hi @statiqantriksh, thanks for reporting this issue. currently military time is not supported, we'll fix it in the next release.
How are you testing your implementation? do you have another OCPI server/client available?

**Comment by statiqantriksh** [comment]
@HamedAkhavan 
Hey we have a database with values as per the standard and the adapters handle the validation mostly and for the issue mentioned above I had to refer to the documentation.
Some of our emsp's also report the issue ( acting as client )

The idea for having a test client sounds good, please let me know your thoughts for collaboration.

**Comment by statiqantriksh** [comment]
@HamedAkhavan I think is issue was missed in the recent commit.
