### ISSUE TITLE
Authorization token

### ISSUE THREAD

**Issue by andrewdubinyak** [TECHS-Technological-Solutions/ocpi#51]
```
async def add_or_update_location(request: Request, country_code: CiString(2), party_id: CiString(3),
                                 location_id: CiString(36), location: Location,
                                 crud: Crud = Depends(get_crud), adapter: Adapter = Depends(get_adapter)):
    auth_token = get_auth_token(request)

    data = await crud.get(ModuleID.locations, RoleEnum.emsp, location_id, auth_token=auth_token,
                          country_code=country_code, party_id=party_id, version=VersionNumber.v_2_2_1)
    if data:
        data = await crud.update(ModuleID.locations, RoleEnum.emsp, location.dict(), location_id,
                                 auth_token=auth_token, country_code=country_code,
                                 party_id=party_id, version=VersionNumber.v_2_2_1)
    else:
        data = await crud.create(ModuleID.locations, RoleEnum.emsp, location.dict(),
                                 auth_token, country_code=country_code,
                                 party_id=party_id, version=VersionNumber.v_2_2_1)

    return OCPIResponse(
        data=[adapter.location_adapter(data).dict()],
        **status.OCPI_1000_GENERIC_SUCESS_CODE,
    )
```

In this part code "module/locations/v_2_2_1/api/emsp.py" method await crud.create.
Why did you send auth_token in *args ?

**Comment by HamedAkhavan** [comment]
@andrewdubinyak for every crud operation, it may be necessary to know the origin of the request. That's why auth_token is always passed to crud operations. You may ignore unwanted parameters if it's not a requirement in your project.

**Comment by VictorTechs** [comment]
Hello @andrewdubinyak,
Sorry for the long response, could You tell me if Hamed's answer is satisfactory for You?

**Comment by IOR88** [comment]
Hi @andrewdubinyak we are now getting back to ocpi library maintenance, we will soon take care of the request you created, have you successfully integrated ocpi lib with your project ?

**Comment by andrewdubinyak** [comment]
> @andrewdubinyak for every crud operation, it may be necessary to know the origin of the request. That's why auth_token is always passed to crud operations. You may ignore unwanted parameters if it's not a requirement in your project.


Hi @IOR88 ! Thank for you your answer but Im finished the OCPI project.
